/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=beta --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: 3822b1437817a6ee5e05405d8e7b67ae)
interface __BaseEnv_CloudflareBindings {
	APP_ENV: string;
	APP_ORIGIN: string;
	APP_VERSION: string;
	SUPABASE_URL: string;
	SUPABASE_PUBLISHABLE_KEY: string;
	TURNSTILE_SITE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "APP_ORIGIN" | "APP_VERSION" | "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY" | "TURNSTILE_SITE_KEY">> {}
}
